Repository nanjeong-owl/airbnb, pull requests merged in 2022-05, with the labels that each got.

#3 chore: 초기 개발환경 설정
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/index.js
Labels: chore

#4 fix: 운영체제 차이로 인해 linebreak 설정 끔
  .eslintrc.json
  src/App.jsx
Labels: fix

#6 design: Header UI 추가
  package-lock.json
  package.json
  src/App.jsx
  src/components/header/Gnb.jsx
  src/components/header/Header.jsx
  src/components/header/LoginButton.jsx
  src/cylindrical.js
  src/theme.js
Labels: design

#8 7 검색바 UI 구현
  src/App.jsx
  src/components/Boundary.jsx
  src/components/header/CheckIn.jsx
  src/components/header/CheckOut.jsx
  src/components/header/CylindricalBox.jsx
  src/components/header/DateBox.jsx
  src/components/header/GuestBox.jsx
  src/components/header/Header.jsx
  src/components/header/LoginButton.jsx
  src/components/header/PriceBox.jsx
  src/components/header/SearchBar.jsx
  src/cylindrical.js
Labels: design

#10 7 검색바 UI 구현
  src/components/header/CheckIn.jsx
  src/components/header/CheckOut.jsx
  src/components/header/CylindricalBox.jsx
  src/components/header/DateBox.jsx
  src/components/header/GuestBox.jsx
  src/components/header/PriceBox.jsx
  src/components/header/SearchBar.jsx
Labels: feat, design

#12 11 mini 검색바 UI 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/assets/crossIcon.svg
  src/assets/menuIcon.svg
  src/assets/searchIcon.svg
  src/assets/userIcon.svg
  src/components/header/DateBox.jsx
  src/components/header/Gnb.jsx
  src/components/header/GuestBox.jsx
  src/components/header/LoginButton.jsx
  src/components/header/PriceBox.jsx
  src/components/header/SearchBar.jsx
  src/components/header/searchBar/CheckIn.jsx
  src/components/header/searchBar/CheckOut.jsx
  src/components/header/searchBar/CylindricalBox.jsx
  src/components/header/searchBar/DateBox.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/header/searchBar/SearchBar.jsx
Labels: design, refactor, chore

#14 13 1주차 수요일 리뷰 반영
  .eslintrc.json
  src/App.jsx
  src/components/Boundary.jsx
  src/components/header/Header.jsx
  src/components/header/LoginButton.jsx
  src/components/header/searchBar/CheckIn.jsx
  src/components/header/searchBar/CheckOut.jsx
  src/components/header/searchBar/CylindricalBox.jsx
  src/components/header/searchBar/DateBox.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/header/searchBar/SearchBar.jsx
  src/theme.js
Labels: refactor, chore

#16 design: SearchBar modal UI 구현
  src/components/header/modal/CalendarModal.jsx
  src/components/header/modal/GuestModal.jsx
  src/components/header/modal/PriceModal.jsx
Labels: design

#18 design: SearchBar modal UI 구현 중 누락된 파일 추가
  src/Modal.js
  src/components/header/searchBar/CheckIn.jsx
  src/components/header/searchBar/SearchBar.jsx
  src/cylindrical.js
Labels: design

#19 17 router 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/header/searchBar/CheckIn.jsx
  src/components/header/searchBar/CheckOut.jsx
  src/components/header/searchBar/CylindricalBox.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/pages/Search.jsx
  src/pages/home.jsx
Labels: feat, refactor

#22 design: 검색 페이지 숙박시설 리스트 구현
  src/assets/emptyHeart.svg
  src/assets/emptyStar.svg
  src/assets/fullHeart.svg
  src/assets/fullStar.svg
  src/components/main/searchMain/AccomodationHeader.jsx
  src/components/main/searchMain/AccomodationList.jsx
  src/components/main/searchMain/AccomodationListItem.jsx
  src/pages/Search.jsx
  src/util.js
Labels: design
