Repository nanjeong-owl/airbnb, pull requests merged in 2022-06, with the labels that each got.

#27 24 인원 추가 모달 구현
  package-lock.json
  package.json
  src/App.jsx
  src/OptionProvider.jsx
  src/assets/minus.svg
  src/assets/plus.svg
  src/components/Boundary.jsx
  src/components/header/LoginButton.jsx
  src/components/header/modal/GuestModal.jsx
  src/components/header/modal/GuestTab.jsx
  src/components/header/searchBar/CheckOut.jsx
  src/components/header/searchBar/CylindricalBox.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/MiniSearchBar.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/header/searchBar/SearchBar.jsx
  src/components/header/searchBar/SearchPageSeacrhBar.jsx
  src/components/main/searchMain/AccomodationList.jsx
  src/components/main/searchMain/AccomodationListItem.jsx
  src/mockData.js
  src/theme.js
  src/util.js
Labels: feat, design

#28 feat: 달력 모달 구현 중
  src/components/header/modal/CalendarModal.jsx
  src/lib/Calendar.jsx
  src/lib/CalendarContext.jsx
  src/lib/Days.jsx
  src/lib/Month.jsx
  src/lib/Week.jsx
Labels: feat

#29 Calendar PR 반영
  src/components/header/modal/CalendarModal.jsx
  src/lib/Calendar.jsx
  src/lib/Calendar/Days.jsx
  src/lib/Calendar/Month.jsx
  src/lib/Calendar/Week.jsx
  src/lib/CalendarContext.jsx
  src/lib/Days.jsx
  src/lib/util.js
Labels: refactor, rename

#31 25 달력 모달 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/leftArrow.svg
  src/assets/rightArrow.svg
  src/components/header/modal/CalendarModal.jsx
  src/components/header/searchBar/CheckIn.jsx
  src/components/header/searchBar/CheckOut.jsx
  src/components/header/searchBar/CylindricalBox.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/MiniSearchBar.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/header/searchBar/SearchBar.jsx
  src/components/header/searchBar/SearchPageSeacrhBar.jsx
  src/contexts/PeriodProvider.jsx
  src/helper/constants.js
  src/lib/Calendar.jsx
  src/lib/Calendar/Days.jsx
  src/lib/util.js
Labels: feat, fix, design, refactor, rename

#32 26 요금 모달 구현
  mockData.json
  src/App.jsx
  src/assets/pause.svg
  src/components/header/modal/CalendarModal.jsx
  src/components/header/modal/GuestModal.jsx
  src/components/header/modal/GuestTab.jsx
  src/components/header/modal/Modal.js
  src/components/header/modal/PriceGraph.jsx
  src/components/header/modal/PriceModal.jsx
  src/components/header/modal/RangeSlider.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/main/searchMain/AccomodationList.jsx
  src/contexts/OptionProvider.jsx
  src/contexts/PriceProvider.jsx
  src/helper/mockData.js
  src/helper/util.js
  src/pages/Home.jsx
Labels: feat, fix

#34 refactor: typscript 설정
  package-lock.json
  package.json
  src/components/main/searchMain/AccomodationHeader.tsx
  src/components/main/searchMain/AccomodationList.tsx
  src/components/main/searchMain/AccomodationListItem.tsx
  src/icon.d.ts
  src/temp.ts
  tsconfig.json
Labels: refactor, chore
